version: '3.9'
services:
  postgres_db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=JBdragonfire1135
      - POSTGRES_DB=dandelion_go
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:JBdragonfire1135@postgres_db:5432/dandelion_go?sslmode=disable
