DROP TABLE IF EXISTS "votes";
DROP TABLE IF EXISTS "user_rooms";
DROP TABLE IF EXISTS "rooms";
DROP TABLE IF EXISTS "movie_genres";
DROP TABLE IF EXISTS "movies";
DROP TABLE IF EXISTS "series";
DROP TABLE IF EXISTS "genres";
DROP TABLE IF EXISTS "users";