CREATE TABLE movies_series (
  id INTEGER PRIMARY KEY,
  movie_id INTEGER NOT NULL,
  series_id INTEGER NOT NULL
);

ALTER TABLE movies DROP COLUMN series_id;

ALTER TABLE users ALTER COLUMN id SET NOT NULL;
ALTER TABLE users ALTER COLUMN username SET NOT NULL;

ALTER TABLE genres ALTER COLUMN id SET NOT NULL;
ALTER TABLE genres ALTER COLUMN name SET NOT NULL;

ALTER TABLE series ALTER COLUMN id SET NOT NULL;
ALTER TABLE series ALTER COLUMN name SET NOT NULL;
ALTER TABLE series ALTER COLUMN thumbnail SET NOT NULL;

ALTER TABLE movies ALTER COLUMN id SET NOT NULL;
ALTER TABLE movies ALTER COLUMN title SET NOT NULL;
ALTER TABLE movies ALTER COLUMN duration SET NOT NULL;
ALTER TABLE movies ALTER COLUMN description SET NOT NULL;
ALTER TABLE movies ALTER COLUMN actor_avatars SET NOT NULL;
ALTER TABLE movies ALTER COLUMN trailer SET NOT NULL;
ALTER TABLE movies ALTER COLUMN file_path SET NOT NULL;
ALTER TABLE movies ALTER COLUMN thumbnail SET NOT NULL;
ALTER TABLE movies ALTER COLUMN views SET NOT NULL;
ALTER TABLE movies ALTER COLUMN stars SET NOT NULL;
ALTER TABLE movies ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE movie_genres ALTER COLUMN movie_id SET NOT NULL;
ALTER TABLE movie_genres ALTER COLUMN genre_id SET NOT NULL;

ALTER TABLE rooms ALTER COLUMN id SET NOT NULL;
ALTER TABLE rooms ALTER COLUMN movie_id SET NOT NULL;
ALTER TABLE rooms ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE rooms ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE votes ALTER COLUMN id SET NOT NULL;
ALTER TABLE votes ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE votes ALTER COLUMN movie_id SET NOT NULL;
ALTER TABLE votes ALTER COLUMN stars SET NOT NULL;
