// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: genre.sql

package database

import (
	"context"
)

const getListGenres = `-- name: GetListGenres :many
SELECT id, name FROM genres
ORDER BY id
LIMIT $1
OFFSET $2
`

type GetListGenresParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetListGenres(ctx context.Context, arg GetListGenresParams) ([]Genre, error) {
	rows, err := q.query(ctx, q.getListGenresStmt, getListGenres, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Genre{}
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
