// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Genre struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Movie struct {
	ID           int32    `json:"id"`
	Title        string   `json:"title"`
	Duration     int32    `json:"duration"`
	Description  string   `json:"description"`
	ActorAvatars []string `json:"actor_avatars"`
	Trailer      string   `json:"trailer"`
	// Path to the movie file
	FilePath string `json:"file_path"`
	// Path to the thumbnail image
	Thumbnail string `json:"thumbnail"`
	// Number of views
	Views int32 `json:"views"`
	// Total star votes
	Stars     int32     `json:"stars"`
	CreatedAt time.Time `json:"created_at"`
}

type MovieGenre struct {
	MovieID int32 `json:"movie_id"`
	GenreID int32 `json:"genre_id"`
}

type MovieHistory struct {
	ID              int32     `json:"id"`
	UserID          int32     `json:"user_id"`
	MovieID         int32     `json:"movie_id"`
	WatchedDuration int32     `json:"watched_duration"`
	LastWatched     time.Time `json:"last_watched"`
}

type MoviesSeries struct {
	ID       int32 `json:"id"`
	MovieID  int32 `json:"movie_id"`
	SeriesID int32 `json:"series_id"`
}

type Room struct {
	ID        int32     `json:"id"`
	MovieID   int32     `json:"movie_id"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

type Series struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	// Path to the thumbnail image
	Thumbnail string `json:"thumbnail"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}

type Vote struct {
	ID      int32 `json:"id"`
	UserID  int32 `json:"user_id"`
	MovieID int32 `json:"movie_id"`
	// Star vote of the user for the movie
	Stars int32 `json:"stars"`
}
