// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Genre struct {
	ID   int32
	Name sql.NullString
}

type Movie struct {
	ID          int32
	Title       sql.NullString
	Description sql.NullString
	// Path to the movie file
	FilePath sql.NullString
	// Path to the thumbnail image
	Thumbnail sql.NullString
	// ID of the series the movie belongs to, can be null
	SeriesID sql.NullInt32
	// Number of views
	Views sql.NullInt32
	// Total star votes
	Stars     sql.NullInt32
	CreatedAt sql.NullTime
}

type MovieGenre struct {
	MovieID int32
	GenreID int32
}

type Room struct {
	ID      int32
	MovieID sql.NullInt32
	// Current time of the movie in seconds
	CurrentTime sql.NullFloat64
	IsPlaying   sql.NullBool
	CreatedAt   sql.NullTime
}

type Series struct {
	ID   int32
	Name sql.NullString
	// Path to the thumbnail image
	Thumbnail sql.NullString
}

type User struct {
	ID       int32
	Username sql.NullString
}

type UserRoom struct {
	ID       int32
	UserID   sql.NullInt32
	RoomID   sql.NullInt32
	JoinedAt sql.NullTime
	LeftAt   sql.NullTime
}

type Vote struct {
	ID      int32
	UserID  sql.NullInt32
	MovieID sql.NullInt32
	// Star vote of the user for the movie
	Stars sql.NullInt32
}
