// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: movie_history.sql

package database

import (
	"context"
	"database/sql"
)

const createMovieHistory = `-- name: CreateMovieHistory :exec
INSERT INTO movie_history
 (user_id,movie_id,watched_duration, last_watched)
VALUES ($1, $2, $3, $4)
`

type CreateMovieHistoryParams struct {
	UserID          sql.NullInt32 `json:"user_id"`
	MovieID         sql.NullInt32 `json:"movie_id"`
	WatchedDuration sql.NullInt32 `json:"watched_duration"`
	LastWatched     sql.NullTime  `json:"last_watched"`
}

func (q *Queries) CreateMovieHistory(ctx context.Context, arg CreateMovieHistoryParams) error {
	_, err := q.exec(ctx, q.createMovieHistoryStmt, createMovieHistory,
		arg.UserID,
		arg.MovieID,
		arg.WatchedDuration,
		arg.LastWatched,
	)
	return err
}

const updateMovieHistory = `-- name: UpdateMovieHistory :exec
UPDATE movie_history
SET watched_duration = $1, last_watched = $2
WHERE movie_id = $3
`

type UpdateMovieHistoryParams struct {
	WatchedDuration sql.NullInt32 `json:"watched_duration"`
	LastWatched     sql.NullTime  `json:"last_watched"`
	MovieID         sql.NullInt32 `json:"movie_id"`
}

func (q *Queries) UpdateMovieHistory(ctx context.Context, arg UpdateMovieHistoryParams) error {
	_, err := q.exec(ctx, q.updateMovieHistoryStmt, updateMovieHistory, arg.WatchedDuration, arg.LastWatched, arg.MovieID)
	return err
}
