// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateMovieHistory(ctx context.Context, arg CreateMovieHistoryParams) error
	GetListGenres(ctx context.Context, arg GetListGenresParams) ([]Genre, error)
	GetListMovies(ctx context.Context, arg GetListMoviesParams) ([]GetListMoviesRow, error)
	GetMovie(ctx context.Context, id int32) (GetMovieRow, error)
	GetMovieHistoryByUserId(ctx context.Context, userID int32) ([]MovieHistory, error)
	GetMoviesByGenre(ctx context.Context, arg GetMoviesByGenreParams) ([]GetMoviesByGenreRow, error)
	GetMoviesBySerie(ctx context.Context, arg GetMoviesBySerieParams) ([]GetMoviesBySerieRow, error)
	GetRecentMovies(ctx context.Context, arg GetRecentMoviesParams) ([]GetRecentMoviesRow, error)
	GetVotesByUser(ctx context.Context, userID int32) ([]Vote, error)
	GetWatchingMovies(ctx context.Context, arg GetWatchingMoviesParams) ([]GetWatchingMoviesRow, error)
	SearchMovies(ctx context.Context, arg SearchMoviesParams) ([]SearchMoviesRow, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
	UpdateMovieHistory(ctx context.Context, arg UpdateMovieHistoryParams) error
}

var _ Querier = (*Queries)(nil)
