// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"
)

type Querier interface {
	GetMovie(ctx context.Context, id int32) (Movie, error)
	GetMoviesByGenre(ctx context.Context, arg GetMoviesByGenreParams) ([]GetMoviesByGenreRow, error)
	GetMoviesBySeries(ctx context.Context, arg GetMoviesBySeriesParams) ([]Movie, error)
	GetRoom(ctx context.Context, id int32) (Room, error)
	ListGenres(ctx context.Context, arg ListGenresParams) ([]Genre, error)
	ListMovies(ctx context.Context, arg ListMoviesParams) ([]Movie, error)
}

var _ Querier = (*Queries)(nil)
