// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: room.sql

package database

import (
	"context"
)

const getRoom = `-- name: GetRoom :one
SELECT id, movie_id, "current_time", is_playing, created_at FROM rooms
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, id int32) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.CurrentTime,
		&i.IsPlaying,
		&i.CreatedAt,
	)
	return i, err
}
