apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-server
  labels:
    app: dandelion-movie-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dandelion-movie-server
  template:
    metadata:
      labels:
        app: dandelion-movie-server
    spec:
      containers:
        - name: movie-container
          image: 008226931786.dkr.ecr.us-east-1.amazonaws.com/dandelion_server:dandelion-movie
          ports:
            - containerPort: 8080
