apiVersion: v1
kind: Service
metadata:
  name: movie-service
  labels:
    app: dandelion-movie-server
spec:
  selector:
    app: dandelion-movie-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  # type cluster IP by default so -> don't have External IP
