# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    name: build image
    runs-on: ubuntu-latest
    steps:
      #  MyNote: all files will be visible to subsequent steps
      - name: Check out code
        uses: actions/checkout@v3
      - name: "Create env file"
        run: |
          touch app.env
          echo "${{ secrets.APP_ENV }}" > app.env
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::008226931786:role/github_action_dandelion
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: dandelion_server
          IMAGE_TAG: dandelion-movie
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG . 
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

# access step output "steps.login-ecr.outputs "
